Add controller tests
mustabbas/blog pull request #2
Opened 2022-01-18 16:50 UTC by mustabbas

###Change Done 

- [ ] Added RSpec as a gem to the project.
- [ ] Created a Request spec file for all controllers.
- [ ] Made sure that for each action you check:
        1. If response status was correct.
        2. If a correct template was rendered.
        3. If the response body includes correct placeholder text.

2022-01-18 17:05 UTC, petudeveloper reviewed
Hi @mustabbas , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not following the General requirements. Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md). 
- [ ] Please add descriptive README file to your project - please use this [template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-18 18:05 UTC, DeliceLydia requested changes
## Hi @mustabbas, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! here are highlights for your project:
- Followed git workflow
- No linter errors


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 18:05 UTC, DeliceLydia commented on spec/requests/posts_spec.rb
> +end
- [ ] Some of your tests are failing please fix them
![fail](https://user-images.githubusercontent.com/44745855/149992989-f48729f0-49a2-45c9-8d1e-4ab96c31810f.png)

2022-01-18 18:05 UTC, DeliceLydia commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] I suggest that you make your README descriptive you can follow this [template](https://github.com/microverseinc/readme-template)

2022-01-18 18:05 UTC, DeliceLydia commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Remember to add how to run tests locally

2022-01-18 20:23 UTC, Emmyn5600 requested changes
Hi @mustabbas 

Great work on making the project requirements 👏 
You've done well implementing some of the project requirements, but there are still some which aren't addressed yet, please work on it and ask for another review.

 ## Required Changes ♻️

- As requested by the previous reviewers, kindly work on the readme file. Use[ the Microverse template](https://github.com/microverseinc/readme-template) to make a descriptive readme file.

## Optional suggestions

- n/a

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-19 07:28 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-01-19 07:29 UTC, merged